# List all the recipes
default:
    @just --list

# Run this once to set up the project
setup:
    cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Build the project
build:
    cmake --build build

run:
    ./build/src/hello_world

debug:
    cmake -B build -DCMAKE_BUILD_TYPE=Debug
    cmake --build build
    gdb -x .gdbinit ./build/src/hello_world

test:
    @just setup
    @just build
    ctest --test-dir build --output-on-failure

watch:
    find . -name "*.c" -o -name "*.h" | entr -c just test

# Clean up
clean:
    rm -rf build
